/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
});
export const Package = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'clientName' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'addTestimonial' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getPackage' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
  'getPopularPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
  });
  const Package = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'clientName' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getPackage' : IDL.Func([IDL.Text], [IDL.Opt(Package)], ['query']),
    'getPopularPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };