/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : [] | [string],
}
export interface Package {
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'isPopular' : boolean,
  'price' : bigint,
}
export interface Testimonial {
  'clientName' : string,
  'company' : string,
  'message' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addPackage' : ActorMethod<
    [string, string, bigint, Array<string>, boolean],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, string, string, bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getPackage' : ActorMethod<[string], [] | [Package]>,
  'getPopularPackages' : ActorMethod<[], Array<Package>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<
    [string, string, [] | [string], string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];